apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mongo-system
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo